# Generated by Django 2.1.7 on 2019-03-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='published_date',
        ),
        migrations.AddField(
            model_name='equipo',
            name='factura_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='activo',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ACTIVO'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=25, verbose_name='MODELO'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serie',
            field=models.CharField(max_length=15, unique=True, verbose_name='SERIE'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='UBICACION'),
        ),
    ]
