# Generated by Django 2.1.7 on 2019-03-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20190319_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='tipo',
            field=models.CharField(choices=[('mantenimiento', 'mantenimiento'), ('calibracion', 'calibracion'), ('validacion', 'validacion'), ('verificacion', 'verificacion')], default='mantenimiento', max_length=100),
        ),
    ]
