# Generated by Django 2.1.7 on 2019-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20190324_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='hv_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
