# Generated by Django 2.1.7 on 2019-03-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_equipo_hv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='tipo',
            field=models.CharField(blank=True, choices=[('mantenimiento', 'mantenimiento'), ('calibracion', 'calibracion'), ('validacion', 'validacion'), ('verificacion', 'verificacion')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='activo',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='ACTIVO'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cronograma_calibracion',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cronocal/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cronograma_mantenimiento',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cronom/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='factura_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/fact/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='hv_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/hv/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='importacion_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/impor/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='invima_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/inv/%Y/%m/%d/'),
        ),
    ]
