# Generated by Django 2.1.7 on 2019-03-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20190324_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='uploads/imagenes'),
        ),
    ]
