# Generated by Django 2.1.7 on 2019-03-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_equipo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='cronograma_calibracion',
            new_name='cronograma_general',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='cronograma_mantenimiento',
            new_name='historico_mantenimiento',
        ),
    ]
