# Generated by Django 2.2 on 2019-04-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_dyh_project_dyh_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyh_project',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
