# Generated by Django 2.2 on 2019-04-21 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0014_auto_20190421_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dyh_project',
            new_name='project',
        ),
        migrations.RenameModel(
            old_name='dyh_task',
            new_name='task',
        ),
    ]
