# Generated by Django 2.2 on 2019-05-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_equipo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, default='media/uploads/imagenes/no_im.jpg', null=True, upload_to='uploads/imagenes'),
        ),
    ]
