# Generated by Django 2.2 on 2019-05-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_auto_20190505_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='activo',
            field=models.CharField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=25, null=True, unique=True, verbose_name='ACTIVO'),
        ),
    ]
