# Generated by Django 2.2 on 2019-05-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_auto_20190505_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cronograma',
        ),
    ]
