# Generated by Django 2.2 on 2019-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_delete_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='activo',
            field=models.CharField(blank=True, help_text=' <strong>Para equipos alquilados ingrese el rango <em>900-999</em>.</strong>', max_length=25, null=True, unique=True, verbose_name='ACTIVO'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='factura_date',
            field=models.DateField(blank=True, help_text='<strong>Por favor usar el siguiente formsto: <em>DD-MM-YYYY</em>.</strong>', null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(default='media/uploads/imagenes/no_im.jpg', upload_to='uploads/imagenes'),
        ),
    ]
