# Generated by Django 2.2 on 2019-05-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_auto_20190505_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, default='uploads/imagenes/no_im.jpg', null=True, upload_to='uploads/imagenes'),
        ),
    ]
