# Generated by Django 2.2 on 2019-06-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_auto_20190613_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='activo',
            field=models.CharField(blank=True, help_text=' <strong>Para Equipos Alquilados Ingrese El Rango <em>De 210 En Adelante</em>.</strong>', max_length=25, null=True, unique=True, verbose_name='ACTIVO'),
        ),
    ]
