# Generated by Django 2.2 on 2019-06-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_auto_20190618_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='observacion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
