# Generated by Django 2.2 on 2019-06-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_equipo_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='factura_file',
            new_name='archivo_factura',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='hv_file',
            new_name='archivo_hoja_de_vida',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='importacion_file',
            new_name='archivo_importacion',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='invima_file',
            new_name='arhivo_invima',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='factura_date',
            new_name='fecha_factura',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='pais',
        ),
    ]
