# Generated by Django 2.2 on 2019-06-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_auto_20190624_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='uploads/fact/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='archivo_hoja_de_vida',
            field=models.FileField(blank=True, null=True, upload_to='uploads/hv/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='archivo_importacion',
            field=models.FileField(blank=True, null=True, upload_to='uploads/impor/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='arhivo_invima',
            field=models.FileField(blank=True, null=True, upload_to='uploads/inv/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cronograma_general',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cronocal/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='historico_mantenimiento',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cronom/%Y/%m/'),
        ),
    ]
