# Generated by Django 2.2.3 on 2019-07-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_auto_20190624_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='guia_rapida',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no'), ('N/A', 'N/A')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='mantenimiento',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no'), ('N/A', 'N/A')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='observacion',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
